export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_LIST_CATEGORIA1_REQUEST =
  "PRODUCT_LIST_CATEGORIA1_REQUEST";
export const PRODUCT_LIST_CATEGORIA1_SUCCESS =
  "PRODUCT_LIST_CATEGORIA1_SUCCESS";
export const PRODUCT_LIST_CATEGORIA1_FAIL = "PRODUCT_LIST_CATEGORIA1_FAIL";

export const PRODUCT_LIST_CATEGORIA2_REQUEST =
  "PRODUCT_LIST_CATEGORIA2_REQUEST";
export const PRODUCT_LIST_CATEGORIA2_SUCCESS =
  "PRODUCT_LIST_CATEGORIA2_SUCCESS";
export const PRODUCT_LIST_CATEGORIA2_FAIL = "PRODUCT_LIST_CATEGORIA2_FAIL";

export const PRODUCT_LIST_CATEGORIA3_REQUEST =
  "PRODUCT_LIST_CATEGORIA3_REQUEST";
export const PRODUCT_LIST_CATEGORIA3_SUCCESS =
  "PRODUCT_LIST_CATEGORIA3_SUCCESS";
export const PRODUCT_LIST_CATEGORIA3_FAIL = "PRODUCT_LIST_CATEGORIA3_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";
